const AppStyles = {
    color: {
        yellow: '#FFB509',
        yellowDark: '#EEA600',
        placeholder: '#E0E0E0',
        error: '#FF8282',
        white: '#FFFFFF',
        black: '#000000',
        gray: '#bbb',
        transparent: 'transparent',
        low_gray: '#E0E0E0',
        dark_gray: '#404040',
        dark_mode: '#1A1A1A',
        bg_low_gray: '#F5F7FA',
        default_bg: '#fff',
        info: '#00C1FB',
        success: '#00B865',
        cyan: '#00C1FB',
    },
    font: {
        size: {
            default: 16,
            error: 14,
            small: 10,
            medium: 15,
            large: 20,
            xlarge: 25,
            xxlarge: 30,
            xxxlarge: 35,
        },
        weight: {
            light: '300',
            regular: '400',
            medium: '500',
            bold: '700',
            black: '900'
        }
    },
    padding: {
        small: 5,
        medium: 10,
        large: 15,
        xlarge: 20,
        xxlarge: 25,
        xxxxlarge: 45,
    },
    margin: {
        small: 5,
        medium: 10,
        large: 15,
        xlarge: 20,
        xxlarge: 25,
        xxxxlarge: 30,
    },
    inputBorderRadius: {
        default: 5,
        small: 1,
        medium: 2,
        large: 3,
        xlarge: 4,
        xxlarge: 5,
        xxxxlarge: 6,
    },
    inputHeight: {
        default: 45,
        small: 40,
        medium: 50,
        large: 60,
        xlarge: 70,
        xxlarge: 80,
        xxxxlarge: 90,
    },
    fontFamily: {
        default: 'Roboto',
        bold: 'Roboto-Bold',
        light: 'Roboto-Light',
        medium: 'Roboto-Medium',
        black: 'Roboto-Black',
        italic: 'Roboto-Italic',
    },
    borderRadius: {
        default: 5,
        small: 1,
        medium: 2,
        large: 3,
        xlarge: 4,
        xxlarge: 5,
        xxxxlarge: 6,
    }
}

export default AppStyles;